// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"
)

type User struct {
	ID        int32
	Username  string
	Password  string
	Email     string
	CreatedOn time.Time
	LastLogin time.Time
	FirstName string
	LastName  string
}
